# 1、demo1 create ndarray

In [19]:
import numpy as np

# 直接创建数组
arr1 = np.array([1, 2, 3, 4,5])
print(arr1)
print(type(arr1))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
# arange函数创建
arr2 = np.arange(0, 10, 2) # 0-9，步长为2
print(arr2)
print(type(arr2))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [21]:
# 创建值全为0/1的数组
arr3 = np.zeros(10)
print(arr3)

arr4 = np.ones(10)
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# 2、demo2 attr

In [22]:
import numpy as np

# 数组属性、遍历方式
arr1 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print("数组形状：", arr1.shape) # 输出数组形状
print("数组维度", arr1.ndim) # 输出数组维度
print('数组元素个数', arr1.size) # 输出数组元素个数
print('数组元素类型', arr1.dtype) # 输出数组元素类型

# 索引遍历

数组形状： (2, 2, 3)
数组维度 3
数组元素个数 12
数组元素类型 int64
