# 一、概述

- numpy完全标准C语言实现，运行效率迅速

## 1、发展历史

## 2、核心：多维数组

- 向量：一维数组
- 矩阵：二维数组
- 张量：三维数组

# 二、基础

## 1、`ndarray`

In [4]:
# demo1 create ndarray
import numpy as np

# 直接创建数组
arr1 = np.array([1, 2, 3, 4,5])
print(arr1)
print(type(arr1))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# arange函数创建
arr2 = np.arange(0, 10, 2) # 0-9，步长为2
print(arr2)
print(type(arr2))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [6]:
# 创建值全为0/1的数组
arr3 = np.zeros(10)
print(arr3)

arr4 = np.ones(10)
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
