# 1、`create ndarray`

In [19]:
import numpy as np

# 直接创建数组
arr1 = np.array([1, 2, 3, 4,5])
print(arr1)
print(type(arr1))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
# arange函数创建
arr2 = np.arange(0, 10, 2) # 0-9，步长为2
print(arr2)
print(type(arr2))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [21]:
# 创建值全为0/1的数组
arr3 = np.zeros(10)
print(arr3)

arr4 = np.ones(10)
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# 2、`attr`

In [22]:
import numpy as np

# 数组属性、遍历方式
arr1 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print("数组形状：", arr1.shape) # 输出数组形状
print("数组维度", arr1.ndim) # 输出数组维度
print('数组元素个数', arr1.size) # 输出数组元素个数
print('数组元素类型', arr1.dtype) # 输出数组元素类型

数组形状： (2, 2, 3)
数组维度 3
数组元素个数 12
数组元素类型 int64


In [23]:
# 索引访问
print("第一页：", arr1[0])
print("第一页 第一行：", arr1[0][0])
print("第一页 第一行 第一列：", arr1[0][0][0])
print(arr1[0, 0, 1])

第一页： [[1 2 3]
 [4 5 6]]
第一页 第一行： [1 2 3]
第一页 第一行 第一列： 1
2


In [24]:
# for循环遍历
for i in range(arr1.shape[0]): # 遍历每一页
    for j in range(arr1.shape[1]): # 遍历每一行
        for k in range(arr1.shape[2]): # 遍历每一列
            print(arr1[i][j][k], end=' ')
        print()

1 2 3 
4 5 6 
7 8 9 
10 11 12 


# 3、`multi type`

In [25]:
import numpy as np

data = [
    ('zs', [90, 80, 85], 15),
    ('ls', [92, 81, 83], 16),
    ('ww', [95, 85, 95], 18)
]

- 方式1

In [26]:
# U3：长度为3的Unicode字符串
# 3int32：3个int32类型数字
# int32：int32类型数字
arr1 = np.array(data, dtype="U3, 3int32, int32")
print(arr1)
print(arr1[0]['f0'])
print(arr1[1]['f1'])

[('zs', [90, 80, 85], 15) ('ls', [92, 81, 83], 16)
 ('ww', [95, 85, 95], 18)]
zs
[92 81 83]


- 方式2

In [27]:
 # dtype中定义(名称, 类型, 长度)
arr2 = np.array(data, dtype=[('name', 'str_', 2), ('score', 'int32', 3), ('age', 'int32', 1)])
print(arr2)
print(arr2['name']) # 打印name列
print(arr2['score']) # 打印score列
print(arr2['age']) # 打印age列

[('zs', [90, 80, 85], [15]) ('ls', [92, 81, 83], [16])
 ('ww', [95, 85, 95], [18])]
['zs' 'ls' 'ww']
[[90 80 85]
 [92 81 83]
 [95 85 95]]
[[15]
 [16]
 [18]]


- 方式3

In [28]:
# 名称和类型分开定义
arr3 = np.array(data, dtype={"names":["name", "score", "age"], "formats":["U3", "3int32", "int32"]})
print(arr3[0]['name']) # 打印第一个人的名字
print(arr3[1]['score']) # 打印第二个人的成绩

zs
[92 81 83]


- 方式4

In [29]:
arr4 = np.array(data, dtype={'names':('U3', 0), 'scores':('3int32', 16), 'age':('int32', 28)})
print(arr4[0]['names']) # 打印第一个人的名字
print(arr4[0]['scores']) # 打印第一个人的成绩
print(arr4.itemsize) # 打印数组中每个元素的字节数

zs
[90 80 85]
32


# 4、`date type`

In [30]:
import numpy as np

f1 = np.array(['2020', '2020-01-01', '2021-01-01 01:01:01', '2020-02-01'])
f2 = f1.astype("M8[D]") # 转换为天数类型
print(f2)
f3 = f2.astype("int32") # 转换为int32类型，表示距离1970年1月1日的天数
print(f3)
f4 = f1.astype("M8[s]").astype("int32")
print(f4)
print(f2[3] - f2[0]) # 计算两个日期的差值

['2020-01-01' '2020-01-01' '2021-01-01' '2020-02-01']
[18262 18262 18628 18293]
[1577836800 1577836800 1609462861 1580515200]
31 days


# 5、`reshape`

- 视图变维：不会复制数据部分
- 复制变维：复制数据部分

In [31]:
import numpy as np

arr1 = np.arange(1, 9)
print(arr1)
print(arr1.shape)

[1 2 3 4 5 6 7 8]
(8,)


In [32]:
arr2 = arr1.reshape(2, 4)
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [33]:
arr3 = arr2.reshape(2, 2, 2)
print(arr3)
print(arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [34]:
arr4 = arr3.ravel() # 将多维数组转换为一维数组
print(arr4)

[1 2 3 4 5 6 7 8]


In [35]:
arr5 = arr3.flatten() # 将多维数组转换为一维数组，返回一个新的数组
print(arr5)

[1 2 3 4 5 6 7 8]


In [36]:
arr1 += 10
print("arr1：", arr1)
print("arr2：", arr2)
print("arr3：", arr3)
print("arr4：", arr4)
print("arr5：", arr5) # arr5不受arr1影响，因为arr5是arr1的副本

arr1： [11 12 13 14 15 16 17 18]
arr2： [[11 12 13 14]
 [15 16 17 18]]
arr3： [[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]
arr4： [11 12 13 14 15 16 17 18]
arr5： [1 2 3 4 5 6 7 8]


# 6、`slice`

In [38]:
# 数组切片规则与Python列表一致
import numpy as np

arr1 = np.arange(1, 10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [40]:
print(arr1[:3]) # 取前3个元素
print(arr1[3:6]) # 取第4到第6个元素
print(arr1[6:]) # 取第7到最后一个元素

[1 2 3]
[4 5 6]
[7 8 9]


In [43]:
print(arr1[::-1]) # 反转数组
print(arr1[:-4:-1]) # 取倒数第4到最后一个元素（不包含倒数第4个），步长为-1
print(arr1[-7::-1]) # 取倒数第7到第1个元素（不包含倒数第7个），步长为-1

[9 8 7 6 5 4 3 2 1]
[9 8 7]
[3 2 1]


In [44]:
print(arr1[::2]) # 取偶数位置的元素

[1 3 5 7 9]


# 7、`slice 2`

In [46]:
# 多维数组切片与索引
import numpy as np

arr1 = np.arange(1, 28) # 创建1-27的数组
arr1.resize(3, 3, 3) # 重塑为3*3*3的数组
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
print(arr1[1, :, :]) # 第2维度，所有行，所有列

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
print(arr1[:, 1, :]) # 所有维度，第2行，所有列

[[ 4  5  6]
 [13 14 15]
 [22 23 24]]


In [53]:
print(arr1[0, :, 1]) # 第1维度，所有行，第2列

[2 5 8]


# 7、`mask`

掩码操作：比作筛子，即把True位置上的元素保留，False位置上的元素丢弃

In [56]:
import numpy as np

arr1 = np.arange(1, 6, 1)
print(arr1)
mask = [True, False, True, False, False] # 掩码数组
print(arr1[mask])

[1 2 3 4 5]
[1 3]


In [57]:
# 实际运用中，mask一般通过计算获取
mask = (arr1 >= 3)
print(mask)

[False False  True  True  True]
