# 1、最大最小值归一化

In [16]:
import numpy as np
from sklearn import datasets

In [17]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

print(np.max(x[:, 0]))
print(np.min(x[:, 0]))

x[:, 0] = (x[:, 0] - np.min(x[:, 0])) / (np.max(x[:, 0]) - np.min(x[:, 0]))
print(x[:5, 0])

x[:, 1] = (x[:, 1] - np.min(x[:, 1])) / (np.max(x[:, 1]) - np.min(x[:, 1]))
x[:, 2] = (x[:, 2] - np.min(x[:, 2])) / (np.max(x[:, 2]) - np.min(x[:, 2]))
x[:, 3] = (x[:, 3] - np.min(x[:, 3])) / (np.max(x[:, 3]) - np.min(x[:, 3]))

print(x[:5])


7.9
4.3
[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444]
[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


# 2、零均值归一化

In [18]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

np.mean(X[:, 0])
np.std(X[:, 0])

X[:, 0] = (X[:, 0] - np.mean(X[:, 0])) / np.std(X[:, 0])
print(X[:5, 0])
print('-'*100)
print(np.mean(X[:, 0]))
print('-'*100)
print(np.std(X[:, 0]))

X[:, 1] = (X[:, 1] - np.mean(X[:, 1])) / np.std(X[:, 1])
X[:, 2] = (X[:, 2] - np.mean(X[:, 2])) / np.std(X[:, 2])
X[:, 3] = (X[:, 3] - np.mean(X[:, 3])) / np.std(X[:, 3])

print(X[:5])

[-0.90068117 -1.14301691 -1.38535265 -1.50652052 -1.02184904]
----------------------------------------------------------------------------------------------------
-4.736951571734001e-16
----------------------------------------------------------------------------------------------------
1.0
[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


# 3、sklearn归一化

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

scaler = StandardScaler()
scaler.fit(X)
print(scaler.mean_) # mean
print(scaler.scale_) # std

X = scaler.transform(X)
print(X[:5])

[5.84333333 3.05733333 3.758      1.19933333]
[0.82530129 0.43441097 1.75940407 0.75969263]
[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]
